# 에러 처리의 필요성

- 에러는 언제나 발생가능하며, 발생한 에러에 대해 처리하지 않고 방치하면 프로그램은 강제로 종료된다. (이를 막기 위해 try...catch문을 사용하여 강제종료를 피할 수 있다.)
- 직접적인 에러를 발생하지는 않는 예외적인 상황이 발생할 수 있다.
- 예외적인 상황에 적절하게 대응하지 않으면 에러로 이어질 가능성이 높다.
  - 언제나 예외가 발생할 수 있다는 전제하에 대응코드를 작성하는 것이 중요하다.

# try...catch...finally 문

기본적으로 에러 처리를 구현하는 방법은 두가지가 있다.

1. if 문이나 단축 평가 또는 옵셔널 체이닝 연산자를 통해 확인하여 처리하는 방법
2. 에러 처리 코드를 미리 등록해두고 에러가 발생하면 에러 처리 코드로 점프하도록 하는 방법
   - try ...catch...finally문 사용
   - 일반적으로 이 방법을 에러 처리라고 한다.

```javascript
try {
  // 실행할 코드
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
}
```

## Error 객체

Error 생성자 함수는 에러 객체를 생성한다. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있다.

`const error = new Error('invalid');`

- Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 갖는다.
- message 프로퍼티의 값은 Error생성자 함수에 인수로 전달한 에러 메시지이고, stack 프로퍼티의 값은 에러를 발생시킨 콜스택의 호출정보를 나타내는 문자열이며 디버깅 목적으로 사용한다.
- 자바스크립트는 Error 생성자 함수를 포함하여 7가지의 에러 객체를 생성할 수 있는 생성자 함수를 제공한다.
  - Error, SyntaxError, ReferenceError, TypeError, RangeError, URIError, EvalError

## throw 문

Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다.
에러를 발생시키려면 try 코드 블록에서 throw문으로 에러 객에를 던져야 한다.

```javascript
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error("something wrong");
} catch (error) {
  console.log(error); // Error: something wrong
}
```

## 에러의 전파

에러는 호출자 방향으로 전파된다. 즉 콜 스택의 아래 방향으로 전파된다.

```javascript
const first = () => {
  throw Error("first에서 발생한 에러"); //
};

const second = () => {
  first();
};

try {
  second();
} catch (err) {
  console.error(err);
}
```
